# Generated by Django 3.0.4 on 2020-03-14 11:11

from django.db import migrations, models
import django.utils.timezone
import django_history.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=256)),
                ('instance_pk', django_history.fields.RemoteField(db_index=True)),
                ('field_name', models.CharField(db_index=True, max_length=256)),
                ('field_value', django_history.fields.RemoteField(null=True)),
                ('added_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-added_at',),
            },
        ),
    ]
